/**
 * Interface for YouTube caption/transcription data
 * Defines the structure for video caption information
 */
export interface YouTubeCaptionData {
  /** YouTube video identifier */
  videoId: string;
  /** Language code of the captions */
  language: string;
  /** Full text content of the captions */
  captions: string;
  /** Whether the captions are auto-generated */
  autoGenerated: boolean;
}

/**
 * Interface for AI service settings
 * Defines configuration for different AI providers
 */
export interface AISettings {
  /** AI provider to use */
  provider: 'openai' | 'claude' | 'gemini' | 'grok';
  /** API key for the AI service */
  apiKey: string;
  /** AI model to use */
  model: string;
  /** Temperature setting for AI responses */
  temperature: number;
}
